---
driver:
  name: vagrant
  ssh:
    insert_key: false
  customize:
    cpus: 1
    memory: 1024

provisioner:
  name: chef_zero
  chef_client_path: /usr/bin/chef-client
  require_chef_omnibus: 12.21.12

transport:
  name: sftp

platforms:
  - name: debian-9.2

suites:
  - name: default
    run_list:
      - recipe[custom_workspace::default]
